=== matiszz/ComputerScience/PTI/XML/carrental.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="carrental">
    <xs:complexType>
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="rental">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="make" type="xs:string" />
                        <xs:element name="model" type="xs:string" />
                        <xs:element name="nofdays" type="xs:unsignedByte" />
                        <xs:element name="nofunits" type="xs:unsignedByte" />
                        <xs:element name="discount" type="xs:unsignedByte" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
     </xs:complexType>
    </xs:element>
</xs:schema>

=== matiszz/ComputerScience/PTI/XML/carrental.xml
<?xml version="1.0" encoding="UTF-8"?>
<carrental xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="carrental.xsd">    <rental>
        <make>Volvo</make>
        <model>45f</model>
        <nofdays>3</nofdays>
        <nofunits>1</nofunits>
        <discount>4</discount>
    </rental>
    <rental>
        <make>Mercedes</make>
        <model>Clase C</model>
        <nofdays>4</nofdays>
        <nofunits>2</nofunits>
        <discount>0</discount>
    </rental>
</carrental>
